# Generated by Django 5.2.6 on 2026-04-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('city_pop', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('ANALISTA', 'Analista de Fraude'), ('EJECUTIVO', 'Ejecutivo (solo lectura)')], db_index=True, default='ANALISTA', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('es_fraude', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('score_riesgo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('explicabilidad', models.JSONField(blank=True, null=True)),
                ('id_transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.transaccion')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_score', models.IntegerField(default=70)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
        ),
    ]
