# Generated by Django 5.2.6 on 2026-04-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='notificaciones_email',
            field=models.BooleanField(default=True, help_text='Enviar emails cuando se detecta fraude'),
        ),
    ]
