# Generated by Django 5.2.6 on 2026-04-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configuracion_notificaciones_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='incidente',
            name='gestionado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_gestionados', to='api.usuario'),
        ),
    ]
