# Generated by Django 6.0.4 on 2026-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_incidente_id_usuario_incidente_gestionado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='age',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='city_pop',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='state',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='avg_historical_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto promedio histórico del cliente', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='card_brand',
            field=models.CharField(default='visa', help_text='Marca: visa, mastercard, amex, diners, other', max_length=20),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='card_type',
            field=models.CharField(default='debit', help_text='Tipo: credit, debit', max_length=10),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='city_population',
            field=models.PositiveIntegerField(default=0, help_text='Población de la ciudad del cliente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='customer_region',
            field=models.CharField(default='lima', help_text='Región/departamento del cliente', max_length=30),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='days_since_first_purchase',
            field=models.PositiveIntegerField(default=0, help_text='Días desde la primera compra del cliente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='eci_code',
            field=models.PositiveSmallIntegerField(default=5, help_text='ECI de autenticación 3DS (0,2,5,6,7,11)'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='has_discount',
            field=models.BooleanField(default=False, help_text='¿El pedido tiene descuento?'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='is_new_customer',
            field=models.BooleanField(default=True, help_text='¿Es primera compra del cliente?'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='issuer_bank',
            field=models.CharField(default='bcp', help_text='Banco emisor peruano', max_length=30),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='num_installments',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de cuotas (0=contado)'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='num_items',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de ítems en el pedido'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='payment_channel',
            field=models.CharField(default='web', help_text='Canal: web, mobile, app', max_length=15),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='previous_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Intentos de pago fallidos previos a este'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='category',
            field=models.CharField(default='otros', help_text='Categoría del producto principal', max_length=32),
        ),
    ]
