# Generated by Django 5.2.6 on 2026-04-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_transaccion_age_remove_transaccion_city_pop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='device_telemetry_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='device_telemetry_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='device_telemetry_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='device_telemetry_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='device_telemetry_5',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='interaction_velocity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Velocidad de interacción', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='session_duration_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duración de la sesión en el portal (minutos)', max_digits=6, null=True),
        ),
    ]
