# Generated by Django 6.0.4 on 2026-05-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaccion_device_telemetry_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='action_code',
            field=models.PositiveSmallIntegerField(default=6, help_text='Código de acción de la pasarela de pago'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='bin',
            field=models.CharField(blank=True, default='404700', help_text='BIN de la tarjeta (primeros 6 dígitos)', max_length=10),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='currency',
            field=models.CharField(default='PEN', help_text='Moneda de la transacción', max_length=5),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='denial_reason',
            field=models.CharField(blank=True, default='unknown', help_text='Razón de denegación (si aplica)', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuento aplicado', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='email_domain',
            field=models.CharField(blank=True, default='gmail.com', help_text='Dominio del email del cliente', max_length=50),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='last_4_digits',
            field=models.CharField(blank=True, default='0000', help_text='Últimos 4 dígitos de la tarjeta', max_length=4),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='product_category',
            field=models.CharField(default='otros', help_text='Categoría del producto principal', max_length=32),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ratio_aar',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, help_text='Amount-to-Average Ratio', max_digits=8),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ratio_asi',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.5, help_text='Authentication Strength Index', max_digits=8),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ratio_cmr',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, help_text='Category Median Ratio', max_digits=8),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ratio_csi',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, help_text='Card Sharing Index', max_digits=8),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ratio_dar',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='Denial-to-Attempt Ratio', max_digits=8),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ratio_dpe',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='Denial Pattern Entropy', max_digits=8),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ratio_vrr',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, help_text='Velocity Risk Ratio', max_digits=8),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='transaction_status',
            field=models.CharField(default='liquidada', help_text='Estado: liquidada, denegada, abandonada', max_length=20),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='wallet_plin',
            field=models.CharField(default='no', help_text='¿Usa Plin? si/no', max_length=3),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='wallet_yape',
            field=models.CharField(default='no', help_text='¿Usa Yape? si/no', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='avg_historical_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='card_type',
            field=models.CharField(default='credito', help_text='Tipo: credito, debito, unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='category',
            field=models.CharField(blank=True, default='otros', help_text='DEPRECATED: usar product_category', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='city_population',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='days_since_first_purchase',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='has_discount',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='interaction_velocity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='is_new_customer',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='payment_channel',
            field=models.CharField(default='pago web', help_text='Canal: pago web, pago movil, app', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='previous_failed_attempts',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='session_duration_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ANALISTA', 'Analista de Fraude'), ('GERENTE', 'Gerente (solo lectura)')], db_index=True, default='ANALISTA', max_length=15),
        ),
    ]
